### ISSUE TITLE
Use UTC timezone for .changes

### ISSUE THREAD

**Issue by zaitor** [openSUSE/osc-plugin-collab#53]
As title says, osc collab should use UTC as timezone and not localtime as it currently does.

**Comment by vuntz** [comment]
Well, the code was supposed to do that, see https://github.com/openSUSE/osc-plugin-collab/blob/master/osc-collab.py#L2500-L2518

Is it not working anymore? (at least, looking at old .changes entries I was submitting years ago, it was working back then)

**Comment by zaitor** [comment]
Nope, it now sets local time - so yeah have broken somewhere in between there

See https://build.opensuse.org/package/view_file/GNOME:Next/four-in-a-row/four-in-a-row.changes?expand=1

or 

https://build.opensuse.org/package/view_file/GNOME:Next/bijiben/bijiben.changes?expand=1
