### ISSUE TITLE
Use https in Source (where possible)

### ISSUE THREAD

**Issue by zaitor** [openSUSE/osc-plugin-collab#54]
Currently osc collab uses http://foo.url and not https://foo.url 

It should use https where possible

**Comment by vuntz** [comment]
This is really something to update for each individual package in the database. Do you have specific examples in mind?

**Comment by zaitor** [comment]
on., 18.09.2019 kl. 09.19 -0700, skrev Vincent Untz:
> This is really something to update for each individual package in the database. Do you have specific examples in mind?
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "https://github.com/openSUSE/osc-plugin-collab/issues/54?email_source=notifications\u0026email_token=ABXE4PRCBKX5HFANNAAJIDDQKJIIRA5CNFSM4IURP4QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7AUFBA#issuecomment-532759172",
> "url": "https://github.com/openSUSE/osc-plugin-collab/issues/54?email_source=notifications\u0026email_token=ABXE4PRCBKX5HFANNAAJIDDQKJIIRA5CNFSM4IURP4QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7AUFBA#issuecomment-532759172",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
Currently collab rewrites Source0:      https://%URL/foo.tar.xz to http://%URL/foo.tar.xz when bumping version.

As far as I can tell, it happens with every package -- So ugh.. that is a mamut task to change each and every url to have https

**Comment by vuntz** [comment]
> Currently collab rewrites Source0: https://%URL/foo.tar.xz to http://%URL/foo.tar.xz when bumping version.

If I remember correctly, the URL is not taken from the spec file, but from the collab database. See for instance https://github.com/openSUSE/osc-plugin-collab/blob/master/server/upstream/upstream-tarballs.txt (which is one part of the source of the database).

That's why I'm asking for which package you see that.

**Comment by zaitor** [comment]
Well I did not keep a log, but for most of the subs we got for updating
gnome to 3.34 it was a change done.

See gsettings-desktop-schemas

https://build.opensuse.org/request/show/728606

evolution-data-server

https://build.opensuse.org/request/show/728372

evolution

https://build.opensuse.org/request/show/728146

**Comment by vuntz** [comment]
@zaitor to get this really fixed, we need the server code to be updated. @DimStar77 may need to help with that...
